export default {
  environment: 'dev',
  host: 'localhost',
  port: 8022,
  pguser: 'postgres',
  pgpassword: 'postgres',
  pgport: 5432,
  pgdb: 'dummy22',
  mongouser: 'user',
  mongopass: 'pass',
  mongoport: 27017,
  mongoAuth: '?authMechanism=DEFAULT',
  mongodb: 'dummy22',
  redisport: 6379,
};
